#!/usr/bin/env python3
r"""Embed the GAP logo into a tool's GUI as base64 PNG constants.

Why this exists
---------------
The GUI rule (CLAUDE.md, Working approach) puts the GAP wordmark and
symbol in every tool window, and the creator's call is that the images
are embedded in the script rather than loaded from assets/ at runtime —
a copied script keeps its branding without carrying the repo alongside,
and kilobytes of image data are not bulk. Hand-maintaining base64 blobs
is not realistic, so this generates them: run it against a tool and it
fills (or refreshes) the LOGO_*_PNG constants from the canonical exports
in assets/logo/png/. Re-run it over every GUI tool if the brand assets
ever change.

How it works
------------
1. logo_wordmark_256.png is resized to the header width (default 180 px
   — keep it above the wordmark's ~160 px minimum usable width, per the
   assets/logo notes in CLAUDE.md) and re-encoded as optimised PNG;
   logo_symbol_64 and logo_symbol_32 are re-encoded at their native
   sizes for the title bar, where the 2.7:1 wordmark cannot survive.

2. Each is base64-encoded and written into the target's
   LOGO_WORDMARK_PNG / LOGO_SYMBOL_64_PNG / LOGO_SYMBOL_32_PNG
   constants — triple-quoted strings in a .py target (Tk's PhotoImage
   decodes base64 PNG natively, so no new imports), single-quoted
   here-strings ($LOGO_..., @'...'@) in a .ps1 target (WinForms decodes
   via Convert.FromBase64String, also with nothing new). A .py target
   with none of the three gets a complete generated block inserted just
   above its `if __name__ == "__main__":` line; a .ps1 target must
   already carry the three placeholder here-strings, since PowerShell
   scripts have no equivalent anchor. A target with some but not all
   of the names is refused rather than half-patched.

3. A patched .py must parse as valid Python before anything is written,
   and line endings are preserved as \n.

Requires Python with Pillow (already required by the repo's image tools).

Usage
-----
    python tools/embed_logo.py tools/prep_photos.py
    python tools/embed_logo.py tools/make_share_folder.ps1
    python tools/embed_logo.py tools/new_tool.py --wordmark-width 200
"""

import argparse
import ast
import base64
import io
import re
import sys
import textwrap
from pathlib import Path

from PIL import Image

ASSETS = Path(__file__).resolve().parent.parent / "assets" / "logo" / "png"
NAMES = ("LOGO_WORDMARK_PNG", "LOGO_SYMBOL_64_PNG", "LOGO_SYMBOL_32_PNG")
HEADER = (
    "# Embedded GAP logo (base64 PNG; Tk decodes it natively). Generated by\n"
    "# tools/embed_logo.py from assets/logo/png - regenerate there if the\n"
    "# brand assets change; never hand-edit.\n")


def png_b64(path, width=None):
    """Return (base64 text, png byte count) for one asset, resized if asked."""
    with Image.open(path) as im:
        im = im.convert("RGBA")
        if width and im.width != width:
            im = im.resize((width, round(im.height * width / im.width)),
                           Image.Resampling.LANCZOS)
        buf = io.BytesIO()
        im.save(buf, format="PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii"), len(buf.getvalue())


def const_text(name, b64, style):
    body = "\n".join(textwrap.wrap(b64, 76))
    if style == "ps1":
        return f"${name} = @'\n{body}\n'@"
    return f'{name} = """\n{body}\n"""'


def main():
    ap = argparse.ArgumentParser(
        description="Fill or refresh a tool's embedded GAP logo constants.")
    ap.add_argument("target", type=Path, help="the .py tool to patch")
    ap.add_argument("--wordmark-width", type=int, default=180, metavar="PX",
                    help="header wordmark width; keep >= ~160 (default 180)")
    args = ap.parse_args()

    src = args.target.read_text(encoding="utf-8")
    blobs = {
        "LOGO_WORDMARK_PNG": png_b64(ASSETS / "logo_wordmark_256.png",
                                     args.wordmark_width),
        "LOGO_SYMBOL_64_PNG": png_b64(ASSETS / "logo_symbol_64.png"),
        "LOGO_SYMBOL_32_PNG": png_b64(ASSETS / "logo_symbol_32.png"),
    }

    style = "ps1" if args.target.suffix.lower() == ".ps1" else "py"
    if style == "ps1":
        def head(n): return rf"^\${n} = @'"
        def whole(n): return rf"^\${n} = @'.*?'@"
    else:
        def head(n): return rf'^{n} = """'
        def whole(n): return rf'^{n} = """.*?"""'

    present = [n for n in NAMES if re.search(head(n), src, flags=re.MULTILINE)]
    if present and len(present) != len(NAMES):
        sys.exit(f"{args.target}: found only {', '.join(present)} - "
                 "refusing to patch a partial set")
    if present:
        for name in NAMES:
            src, count = re.subn(
                whole(name),
                lambda m: const_text(name, blobs[name][0], style),
                src, count=1, flags=re.MULTILINE | re.DOTALL)
            if count != 1:
                sys.exit(f"{args.target}: could not replace {name}")
    elif style == "ps1":
        sys.exit(f"{args.target}: no logo placeholders found. A PowerShell "
                 "target gets the three placeholder here-strings added by "
                 "hand first - see tools/make_share_folder.ps1 for the shape.")
    else:
        anchor = 'if __name__ == "__main__":'
        if anchor not in src:
            sys.exit(f"{args.target}: no '{anchor}' line to insert above")
        block = HEADER + "\n\n".join(
            const_text(n, blobs[n][0], style) for n in NAMES) + "\n\n\n"
        src = src.replace(anchor, block + anchor, 1)

    if style == "py":
        ast.parse(src)  # never write a file that no longer parses
    args.target.write_text(src, encoding="utf-8", newline="\n")
    for name in NAMES:
        print(f"{name}: {blobs[name][1]:5d} bytes PNG -> "
              f"{len(blobs[name][0])} chars base64")
    print(f"wrote {args.target}")


if __name__ == "__main__":
    main()
